### ISSUE TITLE
Sweeping indicator for deposits

### ISSUE THREAD

**Issue by pdyraga** [suntzu93/threshold-tBTC#1]
Once BTC is deposited in the system and P2SH deposit transaction gains enough confirmations, one of the minters can request to mint tBTC optimistically. After the optimistic minting delay, if no guardians canceled the optimistic mint, the same or another minter can finalize the optimistic mint. The depositor receives tBTC.

All those steps are reflected at tbtcscan.com. Finalized optimistic mint is not the final depositing step, though.

After some time, tECDSA wallet begins a sweep. Sweep unlocks P2SH deposit UTXO and relocsks Bitcoin under the wallet's main P2PKH UTXO. This action is happening on Bitcoin chain. The SPV proof of this action is submitted to Ethereum once there are at least 6 confirmations.

Example of a sweep transaction and an SPV proof:
https://live.blockcypher.com/btc/tx/00540ecc83c1e4988c0d2fd51504abfdb780dce5563f69431c9debd536ed9b59/
https://etherscan.io/tx/0x3fa202ca3792010af9dd4cd1e1cf3841ab84c396ddb8b8640b05185f86708acb

It may also happen that if minters are unresponsive, optimistic mint will not happen and tBTC will be minted as a result of a sweep.

It would be really nice to add an indicator for a deposit informing if it's been swept by the wallet.

**Comment by suntzu93** [comment]
Hello, I want to confirm to make sure I understand the issues correctly. We have two scenarios that will be swept:

1. User sends a Deposit transaction -> the transaction fails due to any reason.
2. User sends a Deposit transaction -> guardians approve it -> minters do not respond

Am I missing any other scenarios ?

**Comment by pdyraga** [comment]
Sweeping happens *always* and in the background. It may happen before or after optimistic minting. It may also happen when there was no optimistic minting if, for example, all minters became unresponsive. 

Sweeping happens every few days and is done by the wallet. All deposits are P2SH UTXOs. They are swept by the wallet by combining them into a single main wallet UTXO.

See here: https://github.com/keep-network/tbtc-v2/blob/main/docs/rfc/rfc-1.adoc#23-depositing

**Comment by suntzu93** [comment]
I see that there are some Deposits that have already been completed and their minting has been finalized, but they are still in the swept transaction, can you explain ?

example :
Deposit ID : 0xbd4a548929355363d422fd0c9a31b1c8e44ac6725cd5a3adcc4c901f707e39f5
Swept transaction : [transaction](https://etherscan.io/tx/0x9aaf5c6336c961e37bce66d95bf7a6db40b511c048c37d333fcd656d5974c07c)

**Comment by pdyraga** [comment]
All deposits need to be swept, regardless if tBTC was optimistically minted for them or not. This has two main effects: it consolidates the UTXO set and it disables the refund from the P2SH script (currently set to 9 months if the deposit wasn't swept by the wallet). The optimistic minting is called *optimistic* because it happens when minters/guardians validate the wallet will be able to sweep the deposit in the future. That's why you see zero tBTC minted in the SPV proof transaction.

**Comment by suntzu93** [comment]
thanks for explain @pdyraga , I have released this feature on site. If you have any suggestions please let me know.

**Comment by pdyraga** [comment]
The update looks great. The only change I would do is to rename "SWEPT COMPLETED" to just "SWEPT". 

I was also considering renaming "MINTING FINALIZED" to "OPTIMISTICALLY MINTED" to better reflect what is happening under the hood given that sweeping can also result in minting if, for the given revealed deposit, minters did not mint tBTC optimistically ([example](https://etherscan.io/tx/0xb0bd217222249f59c84ed0f094f13cf21c1955c6b6e7c6bd00a40d29f29d2382)). After some consideration I think this could be too much. The new status would be longer and might suggest it is somehow related to Optimism L2.

**Comment by suntzu93** [comment]
Thank you for your suggestion. I have updated it.

**Comment by pdyraga** [comment]
Oops, I just realized this issue should be opened in https://github.com/suntzu93/tbtcv2_website_info repo. Sorry!

**Comment by suntzu93** [comment]
> Oops, I just realized this issue should be opened in https://github.com/suntzu93/tbtcv2_website_info repo. Sorry!

it's ok to open this issue here because I also have to upgrade subgraph for this.
